<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTBEsrN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTBEsrN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTBEsrN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTBEsrN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXTBEsrN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XTBEsrN',
    'container.build_id' => '4dec4c98',
    'container.build_time' => 1649711930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTBEsrN');
