<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fournisseur extends \App\Entity\Fournisseur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'idFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'nomFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'domaineFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'numTelFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'emailFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'adresseFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'imageFile'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'idFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'nomFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'matriculeFiscale', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'domaineFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'numTelFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'emailFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'adresseFournisseur', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'logo', '' . "\0" . 'App\\Entity\\Fournisseur' . "\0" . 'imageFile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fournisseur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFournisseur(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFournisseur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFournisseur', []);

        return parent::getIdFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomFournisseur', []);

        return parent::getNomFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomFournisseur(string $nomFournisseur): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomFournisseur', [$nomFournisseur]);

        return parent::setNomFournisseur($nomFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeFiscale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeFiscale', []);

        return parent::getMatriculeFiscale();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeFiscale(string $matriculeFiscale): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeFiscale', [$matriculeFiscale]);

        return parent::setMatriculeFiscale($matriculeFiscale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaineFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaineFournisseur', []);

        return parent::getDomaineFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaineFournisseur(string $domaineFournisseur): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaineFournisseur', [$domaineFournisseur]);

        return parent::setDomaineFournisseur($domaineFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTelFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTelFournisseur', []);

        return parent::getNumTelFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTelFournisseur(string $numTelFournisseur): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTelFournisseur', [$numTelFournisseur]);

        return parent::setNumTelFournisseur($numTelFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailFournisseur', []);

        return parent::getEmailFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailFournisseur(string $emailFournisseur): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailFournisseur', [$emailFournisseur]);

        return parent::setEmailFournisseur($emailFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseFournisseur', []);

        return parent::getAdresseFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseFournisseur(string $adresseFournisseur): \App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseFournisseur', [$adresseFournisseur]);

        return parent::setAdresseFournisseur($adresseFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

}
