<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWQnpNOd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWQnpNOd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWQnpNOd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWQnpNOd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWQnpNOd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WQnpNOd',
    'container.build_id' => '57d423ab',
    'container.build_time' => 1651138149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWQnpNOd');
