<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerON3XsyA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerON3XsyA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerON3XsyA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerON3XsyA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerON3XsyA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ON3XsyA',
    'container.build_id' => 'd183f160',
    'container.build_time' => 1650734536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerON3XsyA');
