<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_landing_page' => [[], ['_controller' => 'App\\Controller\\LandingPageController::index'], [], [['text', '/landing/page']], [], []],
    'app_forgot_password_request' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::request'], [], [['text', '/reset-password']], [], []],
    'app_check_email' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::checkEmail'], [], [['text', '/reset-password/check-email']], [], []],
    'app_reset_password' => [['token'], ['token' => null, '_controller' => 'App\\Controller\\ResetPasswordController::reset'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/reset-password/reset']], [], []],
    'connexion' => [[], ['_controller' => 'App\\Controller\\SecurityController::connexion'], [], [['text', '/connexion']], [], []],
    'deconnexion' => [[], ['_controller' => 'App\\Controller\\SecurityController::deconnexion'], [], [['text', '/deconnexion']], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], []],
    'app_restaurant' => [[], ['_controller' => 'App\\Controller\\restaurant\\AjoutRestaurantController::index'], [], [['text', '/restaurant']], [], []],
    'app_ajout_restaurant' => [[], ['_controller' => 'App\\Controller\\restaurant\\AjoutRestaurantController::ajouter'], [], [['text', '/ajout/restaurant']], [], []],
    'role' => [[], ['_controller' => 'App\\Controller\\role\\AjoutRoleController::listerRole'], [], [['text', '/role']], [], []],
    'ajout_role' => [[], ['_controller' => 'App\\Controller\\role\\AjoutRoleController::AjouterRole'], [], [['text', '/ajout/role']], [], []],
    'app_employe' => [[], ['_controller' => 'App\\Controller\\utilisateur\\EmployeController::index'], [], [['text', '/employe']], [], []],
    'listEmployes' => [[], ['_controller' => 'App\\Controller\\utilisateur\\EmployeController::afficher'], [], [['text', '/employes']], [], []],
    'app_register_employes' => [[], ['_controller' => 'App\\Controller\\utilisateur\\RegisterEmployesController::index'], [], [['text', '/register/employes']], [], []],
    'ajout_employee' => [[], ['_controller' => 'App\\Controller\\utilisateur\\RegisterEmployesController::AjouterEmployee'], [], [['text', '/ajouter/employee']], [], []],
];
